name: anzan
title: Anzan or mental calculation app
base: core24
version: '0.6.2'
icon: snap/gui/anzan.png
summary: Exercise your mental calculation skills
description: |
  Add or subtract the flashing numbers displayed on screen or voiced over by a TTS API.
  This was designed to help you exercise mental math while visualizing a soroban in your head,
  but you can also use it to train your soroban skills.

contact: solstice.dhiver@sorobanexam.org
issues: https://github.com/solsticedhiver/anzan/issues
source-code: https://github.com/solsticedhiver/anzan
website: https://www.sorobanexam.org/anzan.html
donation: https://www.sorobanexam.org/about.html
license: GPL-3.0-or-later
grade: stable
confinement: strict
platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]

parts:
  anzan:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart
    flutter-channel: stable
    build-packages: [pkg-config, ninja-build, cmake, libgtk-3-dev, clang, libstdc++-12-dev, llvm, lld, liblzma-dev, libgstreamer1.0-dev, libgstreamer-plugins-base1.0-dev]
    stage-packages: [libproxy1v5, libunwind8, libdw1t64]
  cleanup:
    after:
      - anzan
    plugin: nil
    override-prime: |
      find $SNAPCRAFT_PRIME/usr/lib -type f,l -name 'libLLVM*.so*' -delete
      rm -rf "$SNAPCRAFT_PRIME/usr/share/man"
      rm -rf "$SNAPCRAFT_PRIME/usr/share/doc"
      rm -rf "$SNAPCRAFT_PRIME/usr/include"
      rm -rf "$SNAPCRAFT_PRIME/usr/share/perl*"
apps:
  anzan:
    command: anzan
    extensions: [gnome]
    plugs:
      - network
      - desktop
      - wayland
      - x11
      - home
      - audio-playback
      - opengl
    environment:
      # fix for libpxbackend-1.0.so
      LD_LIBRARY_PATH: "$LD_LIBRARY_PATH:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libproxy"

# vim: set et ts=2 sw=2:
