name: App Windows Release

on:
  push:
    branches: [ main ]

jobs:
  windows:
    name: Build and create windows release
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Create version
      id: version
      run: |
        Select-String -Path .\pubspec.yaml -Pattern "^version: (\d+.\d+.\d+)\+\d+"|%{"version=$($_.matches.groups[1].value)"} | Out-File -FilePath $env:GITHUB_OUTPUT -Append
    - name: set HEAD git short sha in config.dart
      run: (Get-content -Raw .\lib\config.dart) -replace 'HEAD', $(${env:GITHUB_SHA}.Substring(0,7)) | Set-Content -NoNewLine -Encoding UTF8 .\lib\config.dart
    - uses: subosito/flutter-action@v2
      if: ${{ !env.ACT }}
      with:
        channel : stable
        cache: true
    - run: flutter pub get
    - run: flutter config --enable-windows-desktop
    - run: flutter build windows --release

    - name: Add Visual C++ Runtime DLLs
      run: |
        Copy-Item "${env:SystemRoot}\System32\msvcp140.dll" -Destination build\windows\x64\runner\Release
        Copy-Item "${env:SystemRoot}\System32\vcruntime140.dll" -Destination build\windows\x64\runner\Release
        Copy-Item "${env:SystemRoot}\System32\vcruntime140_1.dll" -Destination build\windows\x64\runner\Release
      env:
        VCINSTALLDIR: "${{ steps.vcinstalldir.outputs.vcid }}"
    - name: Create setup.exe with Inno
      run: iex "& '${env:ProgramFiles(x86)}\Inno Setup 6\ISCC.exe' .\windows\inno\anzan.iss"
    - name: Rename setup.exe
      run: Rename-Item .\windows\inno\Output\mysetup.exe anzan-windows-setup.exe
    - name: Create a release on GitHub
      if: ${{ !env.ACT }}
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: "./windows/inno/Output/anzan-windows-setup.exe"
        token: "${{ secrets.GH_TOKEN }}"
        tag: "v${{ steps.version.outputs.version }}"
        commit: "${{ github.sha }}"

    - name: Rename main folder
      run: Rename-Item build\windows\x64\runner\Release anzan-${{ steps.version.outputs.version }}
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: 'zip'
        directory: 'build/windows/x64/runner/'
        path: 'anzan-${{ steps.version.outputs.version }}'
        filename: 'anzan-windows_x64.zip'
    - name: Create a release on GitHub
      if: ${{ !env.ACT }}
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: "build/windows/x64/runner/anzan-windows_x64.zip"
        token: "${{ secrets.GH_TOKEN }}"
        tag: "v${{ steps.version.outputs.version }}"
        commit: "${{ github.sha }}"

